# Generated by Django 6.1 on 2026-08-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=150)),
                ('credits', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('semester', models.CharField(choices=[('Spring 2026', 'Spring 2026'), ('Fall 2026', 'Fall 2026'), ('Spring 2027', 'Spring 2027'), ('Fall 2027', 'Fall 2027')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
